### ISSUE TITLE
Praw 3.1.0 needed?

### ISSUE THREAD

**Issue by erocs** [Pentom/modmail_ticketmanager#10]
Today saw "Version 2.1.21 of praw is outdated. Version 3.1.0 was released 5 days ago." Do you think this exception is related?

[2015-07-14T00:48:57] Error when attempting to process modmail replies on line number 602.  Exception:  <type 'exceptions.KeyError'>
[2015-07-14T00:48:57] **\* print_exc:
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 602, in processRequestTrackerRepliesToModMail
    strTicket = ticket['id'].split('/')[1]
KeyError: 'id'

**Comment by erocs** [comment]
Hrm, the ticket seems to be an empty dictionary.

**Comment by Pentom** [comment]
Shouldn't be necessary, no.  At least, I have not updated my test system yet to praw 3.1.0.

If I had to guess, its a permission related error and the response object would show an error here.  For testing purposes, see if this still occurs if your modmail account has full privileges to your ticket manager system.  If its fine after that change, then need to determine -what changed-.  The recent changes I have made should not have impacted that.  If you added a new queue to support the automoderator replies, is there a queue specific search permission we need to add?  

Will take a look later today but start at the permission level and I assume the issue will be addressed.

**Comment by erocs** [comment]
Shouldn't be permissions on RT. The bot account is still in the same group
as everyone else who can access the queues. I'll dig into it more. Just
wanted to run it by you in hopes for the quick answer.  ;)

**Comment by Pentom** [comment]
Did this consistently fail or was it a single failure at this stack?

**Comment by erocs** [comment]
I moved to the new version and that started happening during processing
whenever i started it. I added a check to continue the loop when it sees
the empty dictionary.

**Comment by Pentom** [comment]
Cannot reproduce on my test system but I fully believe it is happening.

Lets try this - log into your ticket manager in a chrome window and -after- logged in visit this url (you will need to change the ip to your domain and the /rt/ to whatever subdirectory you use - you should be able to figure it out easily enough):
http://192.168.25.129/rt/REST/1.0/search/ticket?query=%27CF.{New%20Reddit%20Modmail%20Reply}%27%3E%27%27&orderby=-LastUpdated&format=l

This basically should show you what is being returned from the ticket software and may help getting me the info needed to find this.  I -expect- to see:
RT/4.0.7 200 Ok

No matching results.

If this is what you see, also, we may need to call it via python rtkit to see what comes back but I am positive we can get to the bottom of this.  Lets try just the visible url first and if that doesn't expose the issue will give you a tiny python script that can debug it.

**Comment by erocs** [comment]
I believe there was a config issue that caused this and another issue. -_-  After fixing the other issue this is seeming to run fine now too. I'm going to update praw and then I'll test the automoderator feature.

Thanks for putting up with these spurious config issues.

**Comment by erocs** [comment]
Looks like we'll have to switch to OAuth. Also I have a bug stack to look into after the praw upgrade.

/usr/local/lib/python2.7/dist-packages/praw/decorators.py:88: DeprecationWarning: reddit intends to disable password-based authentication of API clien
ts sometime in the near future. As a result this method will be removed in a future major version of PRAW.

For more information please see:
- Original reddit deprecation notice: https://www.reddit.com/comments/2ujhkr/
- Updated delayed deprecation notice: https://www.reddit.com/comments/37e2mv/

Pass `disable_warning=True` to `login` to disable this warning.
  warn(msg, DeprecationWarning)

**Comment by erocs** [comment]
Ok, the stack when upgrading praw is this issue https://www.reddit.com/r/redditdev/comments/3aybk8/login_error/cskfbx2.

**Comment by erocs** [comment]
Which BTW, upgrading pyOpenSSL from 0.14 to 0.15.1 was enough for now to have it work again.

**Comment by erocs** [comment]
And automoderator feature success test. Thanks!

**Comment by Pentom** [comment]
Thanks for looking into this further - appreciate you closing it out.  

Would it be, perhaps, better for us to separate the configuration out into its own file so it can be managed easier through changes to the main source?

**Comment by erocs** [comment]
I would love it if we split out the config. I think this crept in because of git trying to be too smart while merging changes. It would be a fairly simple change and I wouldn't have to maintain a local 'settings' branch. If you want I can do it.
