### ISSUE TITLE
Can't create tickets

### ISSUE THREAD

**Issue by erocs** [Pentom/modmail_ticketmanager#4]
https://github.com/Pentom/modmail_ticketmanager/blob/master/modmail_ticketmanager.py#L431

Client error.

```
"Error: This login session belongs to a REST client, and cannot be used to
access non-REST interfaces of RT for security reasons.

Please log out and back in to obtain a session for normal browsing.  If
you understand the security implications, disabling RT's CSRF protection
will remove this restriction.
" is not valid
2015-04-28 21:46:30.294963 - Error when attempting to review modmail on line number 194.  Exception:  <type 'exceptions.IndexError'>
*** print_tb:
  File "modmail_ticketmanager.py", line 194, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)
*** print_exception:
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 194, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)
  File "modmail_ticketmanager.py", line 301, in processModMailRootMessage
    ticketId = createTicket(rootAuthor, rootSubject, rootBody, rootResponseUrl)
IndexError: list index out of range
*** print_exc:
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 194, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)
  File "modmail_ticketmanager.py", line 301, in processModMailRootMessage
    ticketId = createTicket(rootAuthor, rootSubject, rootBody, rootResponseUrl)
  File "modmail_ticketmanager.py", line 445, in createTicket
    strTicket = (response.parsed[0][0][1]).split('/')[1]
IndexError: list index out of range
```

By the apache log there's a redirect to outside of the REST API.

```
x.x.x.x - - [28/Apr/2015:17:27:43 -0400] "POST /rt/REST/1.0/ticket/new HTTP/1.1" 302 346 "-" "Python-urllib/2.7"
x.x.x.x - - [28/Apr/2015:17:27:43 -0400] "GET /rt/SelfService/ HTTP/1.1" 200 635 "-" "Python-urllib/2.7"
```

On the box and in their github repo (https://github.com/bestpractical/rt/tree/stable/share/html/REST/1.0/ticket) there's no new handler.

```
root@xxxx:/usr/share/request-tracker4/html/REST/1.0/ticket# ls
comment  link  merge
```

What version of RT were you using for testing?

**Comment by Pentom** [comment]
Reviewing.

**Comment by Pentom** [comment]
I am running RequestTracker 4.0.7 personally and have tested this on 4.2.7.

The /ticket/new url appears to be a valid rest api end point in these versions.  For example, see "http://rt.easter-eggs.org/demos/4.2/REST/1.0/ticket/new" compared to "http://rt.easter-eggs.org/demos/4.2/REST/1.0/ticket/newdafsfasdf" - the '/new' corresponds to a request for an ID and a Queue as expected.  Also note that /ticket/#NUMBER# is valid to review data about a ticket ala:  "http://rt.easter-eggs.org/demos/4.2/REST/1.0/ticket/1"

My assumption, at this time, is that the request tracker url you have is invalid.  Please perform the following tests:
- Create a ticket and find the ticket number.
- Get the URL in "requestTrackerRestApiUrl" variable and append "ticket/______" into it.  Ie - if your ticket is number 1, then an example url is:  "http://192.168.25.129/rt/REST/1.0/ticket/1".  
- Validate that this returns ticket information to you.  If it does not, then your url is incorrect and you need to address.

Note that we are using the official api docuemnted "http://requesttracker.wikia.com/wiki/REST - for info on the ticket create method please check out "http://requesttracker.wikia.com/wiki/REST#Ticket_Create"

Let me know what you find with regards to the ticket api but I assume its a configuration issue.  Dont forget to validate that the requestTrackerQueueToPostTo variable refers to a valid queue id.

**Comment by erocs** [comment]
Thanks for the info.

Poking around some more, the CSRF error is due to the /SelfService/index.html access. Need to figure out why the redirect is occurring.

**Comment by Pentom** [comment]
As issue appears to be a configuration problem, closing this ticket at this time.  Feel free to open a new one if you see a bug or something that appears wrong.

**Comment by erocs** [comment]
Thanks. I just found the config issue and it seems to be working.
