### ISSUE TITLE
Cherry-pick 7dbf1eaf11 from Civcraft

### ISSUE THREAD

**Issue by erocs** [Pentom/modmail_ticketmanager#9]
It moves output from print to the logging module. Sending you a pull request also would migrate all the merge diffs, which I don't know if you would care about.

**Comment by erocs** [comment]
I have an exception to fix so there'll be an update to this pull.

**Comment by erocs** [comment]
There we go. Also take 2248e1a385.

**Comment by Pentom** [comment]
Thanks for the pull.  Will take a look, run my test cases against it, and pull it in.  Pun intended.

**Comment by Pentom** [comment]
Commited in eb2d4617846db206d00bcd335c52912d9ee9480d

Note that I also changed some syntax sugar that was added in python 3 (that you used) that was not present in python 2.6.8.  Targeting that python version for a few reasons though I can be convinced to do away with support for that if there is a legitimate need.

Documented new dependency on argparse.

Everything tests fine, thanks for the pull!
